### ISSUE TITLE
Questions about porting algorithms to architecture search framework

### ISSUE THREAD

**Issue by negrinho** [naszilla/bananas#2]
Hi Colin,

We've recently released a modular architecture search framework and we were looking at getting reference implementations of search algorithms in it. The main selling point is that we have a well-defined language to write search spaces (our [paper](https://arxiv.org/abs/1909.13404) to appear at NeurIPS 2019). Once an algorithm is implemented, it can be applied to arbitrary search spaces that a user may write. I would appreciate some help in moving your algorithms here to our framework (if your code is under the MIT license). The main questions are:
- What search space encodings do you use?
- How do your search algorithms plug into (i.e., interface or query) the search space?
- What information do the search algorithms consume?
Some pointers would be great!

Our search algorithm implementation are based on the `sample` (get an architecture from the search space) and `update` (pass the results back to the searcher and update its state) API.

Do you want to look into it? Here is the [repo](https://github.com/negrinho/deep_architect) and [colab](https://colab.research.google.com/drive/14xZdGB-BbIivdgNje3Gu7ZmK0m4F02kE) notebook. 

Thanks,
Renato

**Comment by crwhite14** [comment]
Hi Renato, your paper looks very interesting. I read your paper & readme, and it looks like BANANAS will fit into the `sample` and `update` framework. BANANAS interacts with the search space in a manner similar to the standard Bayesian Optimization framework, but the computation that happens under the hood is different. I will be in touch.

**Comment by negrinho** [comment]
Definitely reach out with questions. There are details about iteration over hyperparameters of the search space that might seem confusing at first, but should be straightforward to explain once you have specific questions. Interaction with substitution modules may or may not be a problem for BANANAS. If there are no substitution modules though, the set of hyperparameters is always the same and there shouldn't be any problem. Thanks!

**Comment by negrinho** [comment]
Any updates on this? Happy to do some porting myself. Thanks.
