### ISSUE TITLE
Why load the nasbench data file each time running?

### ISSUE THREAD

**Issue by auroua** [naszilla/bananas#6]
In the file `nas_algorithms.py` the `Data` object is created each time run.
```
def run_nas_algorithm(algo_params, metann_params):
    # set up search space
    mp = copy.deepcopy(metann_params)
    ss = mp.pop('search_space')
    search_space = Data(ss)

    # run nas algorithm
    ps = copy.deepcopy(algo_params)
    algo_name = ps.pop('algo_name')

```
This is quite time consuming. Why the data object is created each time run?

**Comment by crwhite14** [comment]
Thanks for the question. We recently fixed this so that the data file is only loaded once.
