### ISSUE TITLE
The performance gap between encode path or not encode path

### ISSUE THREAD

**Issue by auroua** [naszilla/bananas#9]
I have run the bananas ablation test many times with the config of `encode path=True` and `encode path=False`. I can not get the large performance gap between this two case as in the paper `fig5.2`.
I use the default configuration. The following is the evaluated result. `bananas_f` means `bananas` algorithm without encode path.
![Screenshot_2019-12-17_15-31-35](https://user-images.githubusercontent.com/2869412/70974636-2e9e1b00-20e3-11ea-836c-1026f680baa0.png)
How could you get such a big performance gap?

**Comment by crwhite14** [comment]
Hi, There are two differences between the code from the arxiv paper and this version. First, the parameters in get_candidates were a bit different. Second, there was not support to remove isomorphisms for the adjacency matrix encoding (but the path encoding removes isomorphisms automatically by nature). We will explicitly note the difference between removing and not removing isomorphisms for the adjacency matrix encoding in the next iteration of the arxiv paper.

**Comment by auroua** [comment]
Thanks.
